#pragma once

typedef enum key_code {
    // Letters
    KEY_CODE_Q = 0x01,
    KEY_CODE_W,
    KEY_CODE_E,
    KEY_CODE_R,
    KEY_CODE_T,
    KEY_CODE_Y,
    KEY_CODE_U,
    KEY_CODE_I,
    KEY_CODE_O,
    KEY_CODE_P,
    KEY_CODE_A,
    KEY_CODE_S,
    KEY_CODE_D,
    KEY_CODE_F,
    KEY_CODE_G,
    KEY_CODE_H,
    KEY_CODE_J,
    KEY_CODE_K,
    KEY_CODE_L,
    KEY_CODE_Z,
    KEY_CODE_X,
    KEY_CODE_C,
    KEY_CODE_V,
    KEY_CODE_B,
    KEY_CODE_N,
    KEY_CODE_M,

    // Numbers
    KEY_CODE_0,
    KEY_CODE_1,
    KEY_CODE_2,
    KEY_CODE_3,
    KEY_CODE_4,
    KEY_CODE_5,
    KEY_CODE_6,
    KEY_CODE_7,
    KEY_CODE_8,
    KEY_CODE_9,

    // Others
    KEY_CODE_UP,
    KEY_CODE_DOWN,
    KEY_CODE_LEFT,
    KEY_CODE_RIGHT,
    KEY_CODE_LSHIFT,
    KEY_CODE_RSHIFT,
    KEY_CODE_LCTRL,
    KEY_CODE_RCTRL,

    // Letters (lowercase)
    KEY_CODE_a,
    KEY_CODE_b,
    KEY_CODE_c,
    KEY_CODE_d,
    KEY_CODE_e,
    KEY_CODE_f,
    KEY_CODE_g,
    KEY_CODE_h,
    KEY_CODE_i,
    KEY_CODE_j,
    KEY_CODE_k,
    KEY_CODE_l,
    KEY_CODE_m,
    KEY_CODE_n,
    KEY_CODE_o,
    KEY_CODE_p,
    KEY_CODE_q,
    KEY_CODE_r,
    KEY_CODE_s,
    KEY_CODE_t,
    KEY_CODE_u,
    KEY_CODE_v,
    KEY_CODE_w,
    KEY_CODE_x,
    KEY_CODE_y,
    KEY_CODE_z,

    KEY_CODE_UNKNOWN,

    KEY_CODE_MAX_NUM
} key_code;
