function(set_win_compiler)
    if(MSVC)
        message(STATUS "C compiler: MSVC")
        set(CMAKE_SYSTEM_NAME Windows)

        set(CMAKE_C_FLAGS "/W3 /wd5105")
        set(CMAKE_CXX_FLAGS "/W3 /wd5105")
    else()
        find_program(MINGW_GCC gcc)
        if(MINGW_GCC)
            set(CMAKE_SYSTEM_NAME Windows)
            set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
            set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
            set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)
            set(CMAKE_C_FLAGS "-O2 -Wno-gnu-zero-variadic-macro-arguments")
            set(CMAKE_CXX_FLAGS "-O2 -Wno-gnu-zero-variadic-macro-arguments")
        else()
            message(FATAL_ERROR "No supported compiler found on Windows")
        endif()
    endif()
endfunction()

function(set_unix_compiler)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        set(CMAKE_SYSTEM_NAME Linux)
        set(CMAKE_C_COMPILER clang)
        set(CMAKE_CXX_COMPILER clang++)
        set(CMAKE_C_FLAGS "-Wall -Wextra -pedantic -O2 -Wno-gnu-zero-variadic-macro-arguments")
        set(CMAKE_CXX_FLAGS "-Wall -Wextra -pedantic -O2 -Wno-gnu-zero-variadic-macro-arguments")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        set(CMAKE_SYSTEM_NAME Linux)
        set(CMAKE_C_COMPILER gcc)
        set(CMAKE_CXX_COMPILER g++)
        set(CMAKE_C_FLAGS "-Wall -Wextra -pedantic -O2 -Wno-gnu-zero-variadic-macro-arguments")
        set(CMAKE_CXX_FLAGS "-Wall -Wextra -pedantic -O2 -Wno-gnu-zero-variadic-macro-arguments")
    else()
        message(FATAL_ERROR "No supported compiler found on Unix")
    endif()
endfunction()

function(set_apple_compiler)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        set(CMAKE_SYSTEM_NAME Darwin)
        set(CMAKE_C_COMPILER clang)
        set(CMAKE_CXX_COMPILER clang++)
        set(CMAKE_OSX_ARCHITECTURES "arm64")
        set(CMAKE_C_FLAGS "-Wall -Wextra -pedantic -O2 -Wno-gnu-zero-variadic-macro-arguments")
        set(CMAKE_CXX_FLAGS "-Wall -Wextra -pedantic -O2 -Wno-gnu-zero-variadic-macro-arguments")
    else()
        message(FATAL_ERROR "No supported compiler found on MacOS")
    endif()
endfunction()
