include(cmake/env.cmake)

function(platform_setup)
if(WIN32)
    if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
        set_win()
    else()
        set_toolchain_env()
    endif()
elseif(UNIX AND NOT APPLE)
    if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
        set_unix()
    else()
        set_toolchain_env()
    endif()
elseif(APPLE)
    if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
        set_apple()
    else()
        set_toolchain_env()
    endif()
else()
    message(FATAL_ERROR "Unsupported platform")
endif()
endfunction()
